name: widgetbook_documentation_addon
description: "An addon that displays documentation for the widget."
version: 1.0.1+1
homepage: https://github.com/b-fontaine/widgetbook_documentation_addon

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_highlighter: ^0.1.1
  flutter_markdown: ^0.7.6+2
  flutter_resizable_container: ^4.0.0
  google_fonts: ^6.2.1
  markdown: ^7.3.0
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.0
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
